### PR TITLE
py-pydicom: Update to 1.2.1

### PR DESCRIPTION
**Pull request by eborisch**
Just updating the version...

### CODE REVIEW

**Comment by krytarowski** [comment]
Please include (upstream) ChangeLog.

**Comment by eborisch** [comment]
> * Do not derive Dataset from dict (#767)
>   - fixes side effects from initializing with another dataset
> * Added missing dict methods that are passed to the tags dict
> * Adapted documentation to Dataset changes
> * Make sure that the retry order config is reset in the test (#772)

The only changeset (except the actual version bump):
https://github.com/pydicom/pydicom/commit/ce721d0bd5000a0162217638406e3d907ff99cf9

**Comment by eborisch** [comment]
Or do you want that in the commit message?

**Comment by krytarowski** [comment]
It's sufficient to add a link to the original changelog to double-check it by a developer and it's fine.

**Comment by bsiegert** [comment]
Thanks, committed. You can close this now.

**Comment by krytarowski** [comment]
@bsiegert I think you can attach diff message:

`Closes #40` and mirror bot will close it automatically

**Comment by bsiegert** [comment]
Yeah, but I forgot that and now I cannot close it in this way :/

**Comment by eborisch** [comment]
Committed.

**Pull request closed without merging**
