### PR TITLE
Bump rspamd to 2.5

### PR DESCRIPTION
**Pull request by sjorge**

### CODE REVIEW

**Comment by sjorge** [comment]
package seems to work fine on illumos, also compiled on netbsd but did not do a full setup.

**Comment by alarixnia** [comment]
~~~
CMake Error at CMakeLists.txt:419 (MESSAGE):
  Your system does not support getaddrinfo call, please consider upgrading it
  to run rspamd
~~~

~~~
gcc: error: unrecognized command line option '-fuse-ld=lld'; did you mean '-fuse-ld=bfd'?
*** Error code 1

Stop.
make[1]: stopped in /home/nia/pkgsrc/mail/rspamd/work/rspamd-2.5/CMakeFiles/CMakeTmp
gmake: *** [Makefile:121: cmTC_cd509/fast] Error 1
~~~

**Comment by alarixnia** [comment]
Thanks for the PR, but please include a changelog next time.

I'm committing it with this extra patch to fix the build on systems with lld installed.

~~~cmake
$NetBSD$

Avoid specifying a custom linker:
gcc: error: unrecognized command line option '-fuse-ld=lld'; did you mean '-fuse-ld=bfd'?

--- cmake/Toolset.cmake.orig	2020-04-01 13:57:55.000000000 +0000
+++ cmake/Toolset.cmake
@@ -41,8 +41,8 @@ endif ()
 
 option(LINKER_NAME "Linker name or full path")
 
-find_program(LLD_PATH NAMES "ld.lld" "lld")
-find_program(GOLD_PATH NAMES "ld.gold" "gold")
+#find_program(LLD_PATH NAMES "ld.lld" "lld")
+#find_program(GOLD_PATH NAMES "ld.gold" "gold")
 
 if(NOT LINKER_NAME)
     if(LLD_PATH)
~~~

**Comment by sjorge** [comment]
@niacat where do I update the changelog?

Odd, I didn't need the extra patch when i tested in netbsd... is lld not installed by default?

**Comment by alarixnia** [comment]
LLD's not installed by default, unless you build the system in a certain way. I've got the package installed, though...

The next time you send an update you can add the recent contents of `work/rspamd-2.5/ChangeLog` to the commit message. It's just required as part of the pkgsrc commit message policy - if I commit a package update without including the release's changes I get nagging emails from people (:

**Comment by sjorge** [comment]
Ah, probably why I did not run into the issue then. And OK just in the commit message. Got it.

~ sjorge

**Pull request closed without merging**
